#!/usr/bin/env python3
"""
Auto-generated data preparation script.
Experiment: grpo-lora-velvet2b-math
Generated by FineTuning-Envelope

Provides get_train_dataset(), get_eval_dataset(), and get_tokenizer() for train.py.
Caches preprocessed data to ./data_cache/ on first run.
"""
import json
import os
import sys
from pathlib import Path

from datasets import load_dataset, load_from_disk
from transformers import AutoTokenizer

CACHE_DIR = Path("./data_cache")
SENTINEL = CACHE_DIR / ".prepare_done"


def _build_tokenizer():
    """Build and configure the tokenizer."""
    tokenizer = AutoTokenizer.from_pretrained(
        "Almawave/Velvet-2B",
        trust_remote_code=True,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    return tokenizer


def _download_and_cache():
    """Download, preprocess, and cache dataset to disk."""
    CACHE_DIR.mkdir(parents=True, exist_ok=True)

    print("[prepare] Loading dataset: openai/gsm8k")
    dataset = load_dataset(
        "openai/gsm8k",
        name="main",
        split="train",
    )
    dataset = dataset.select(range(min(5000, len(dataset))))


    # Save to disk
    dataset.save_to_disk(str(CACHE_DIR / "train"))

    # Write metadata
    metadata = {
        "train_uri": "openai/gsm8k",
        "num_train_samples": len(dataset),
    }
    (CACHE_DIR / "metadata.json").write_text(json.dumps(metadata, indent=2))

    # Mark as done
    SENTINEL.touch()
    print(f"[prepare] Cached {len(dataset)} train samples to {CACHE_DIR}")


def get_tokenizer():
    """Return a configured tokenizer instance."""
    return _build_tokenizer()


def get_train_dataset():
    """Return the training dataset (from cache if available, otherwise download)."""
    if not SENTINEL.exists():
        _download_and_cache()
    return load_from_disk(str(CACHE_DIR / "train"))


def get_eval_dataset():
    """Return the eval dataset, or None if not configured."""
    return None


if __name__ == "__main__":
    if SENTINEL.exists():
        print(f"[prepare] Cache already exists at {CACHE_DIR}, skipping.")
        print(f"[prepare] Delete {SENTINEL} to force re-preparation.")
    else:
        _download_and_cache()
    sys.exit(0)
