#!/usr/bin/env bash
# Auto-generated launch script
# Experiment: grpo-lora-velvet2b-math
# Technique: grpo
# Framework: trl
# Generated by FineTuning-Envelope
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Install dependencies if not already installed
if [ ! -f ".deps_installed" ]; then
    echo "Installing dependencies..."
    pip install -r requirements.txt
    touch .deps_installed
fi

# Launch training
echo "Starting training: grpo-lora-velvet2b-math"
echo "Technique: grpo | Framework: trl"
echo "Model: Almawave/Velvet-2B"

python train.py
