#!/usr/bin/env python3
"""
Auto-generated training script: GRPO via TRL
Experiment: grpo-lora-velvet2b-math
Generated by FineTuning-Envelope
"""
import json
import os
import sys

import torch
from transformers import AutoModelForCausalLM
from trl import GRPOConfig, GRPOTrainer
from peft import LoraConfig
from prepare import get_train_dataset, get_eval_dataset, get_tokenizer

# ──────────────── L2 Hyperparameter Resolution ────────────────
# These defaults come from Level 1 config. Level 2 (autoresearch) overrides
# them via HPARAM_* environment variables at runtime.

HYPERPARAM_DEFAULTS = {
    "learning_rate": 1e-05,
    "per_device_train_batch_size": 2,
    "warmup_ratio": 0.1,
    "weight_decay": 0.01,
    "num_train_epochs": 3,
    "gradient_accumulation_steps": 4,
    "lr_scheduler_type": "cosine",
    "max_grad_norm": 1.0,
}


def resolve_hyperparams(defaults: dict) -> dict:
    """Resolve hyperparameters: YAML defaults overridden by HPARAM_* env vars."""
    resolved = dict(defaults)
    for key in defaults:
        env_key = f"HPARAM_{key.upper()}"
        env_val = os.environ.get(env_key)
        if env_val is not None:
            default_val = defaults[key]
            if isinstance(default_val, bool):
                resolved[key] = env_val.lower() in ("true", "1", "yes")
            elif isinstance(default_val, int):
                resolved[key] = int(env_val)
            elif isinstance(default_val, float):
                resolved[key] = float(env_val)
            else:
                resolved[key] = env_val
    return resolved


hparams = resolve_hyperparams(HYPERPARAM_DEFAULTS)

# ──────────────── Structured Output (L2 contract) ────────────────

STRUCTURED = os.environ.get("ENVELOPE_STRUCTURED_OUTPUT", "false").lower() == "true"
RUN_ID = os.environ.get("RUN_ID", "standalone")


def emit(marker: str, data):
    """Emit structured output for Level 2 parsing."""
    if STRUCTURED:
        if isinstance(data, dict):
            print(f"{marker}: {json.dumps(data)}", flush=True)
        else:
            print(f"{marker}: {data}", flush=True)


emit("EXPERIMENT_STATUS", "STARTED")
emit("EXPERIMENT_RUN_ID", RUN_ID)
emit("EXPERIMENT_HYPERPARAMS", hparams)

# ──────────────── Model ────────────────

print(f"Loading model: Almawave/Velvet-2B")
model = AutoModelForCausalLM.from_pretrained(
    "Almawave/Velvet-2B",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
    attn_implementation="flash_attention_2",
)

tokenizer = get_tokenizer()
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token


# ──────────────── PEFT ────────────────

peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=['q_proj', 'k_proj', 'v_proj', 'o_proj'],
    bias="none",
    task_type="CAUSAL_LM",
)

# ──────────────── Dataset ────────────────

print("Loading dataset from prepare.py cache...")
dataset = get_train_dataset()
eval_dataset = get_eval_dataset()

# ──────────────── Reward Functions ────────────────

# Import reward functions from the rewards/ directory
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Reward: math_correctness (weight=1.0)
try:
    from rewards.math_correctness import reward_fn as _math_correctness_fn
except ImportError:
    def _math_correctness_fn(completions, **kwargs):
        return [0.0] * len(completions)
    print(f"WARNING: Could not import reward 'math_correctness', using zero reward")


def reward_function(completions, **kwargs):
    """Combined reward function with weighted components."""
    rewards = [0.0] * len(completions)
    partial = _math_correctness_fn(completions, **kwargs)
    rewards = [r + 1.0 * p for r, p in zip(rewards, partial)]
    return rewards

reward_funcs = [reward_function]

# ──────────────── Training Config ────────────────

training_config = GRPOConfig(
    output_dir="./output",
    # Technique-specific args
    num_generations=8,
    max_completion_length=512,
    temperature=1.0,
    # L2-tunable hyperparameters (overridable via HPARAM_* env vars)
    learning_rate=hparams["learning_rate"],
    per_device_train_batch_size=int(hparams["per_device_train_batch_size"]),
    warmup_ratio=hparams["warmup_ratio"],
    weight_decay=hparams["weight_decay"],
    num_train_epochs=int(hparams["num_train_epochs"]),
    gradient_accumulation_steps=int(hparams["gradient_accumulation_steps"]),
    lr_scheduler_type=hparams["lr_scheduler_type"],
    max_grad_norm=hparams["max_grad_norm"],
    # Fixed settings from L1 config
    gradient_checkpointing=True,
    bf16=True,
    fp16=False,
    logging_steps=10,
    save_strategy="steps",
    save_steps=500,
    save_total_limit=3,
    report_to=['tensorboard'],
    seed=42,
)

# ──────────────── Train ────────────────

print("Starting GRPO training...")
trainer = GRPOTrainer(
    model=model,
    args=training_config,
    reward_funcs=reward_funcs,
    train_dataset=dataset,
    eval_dataset=eval_dataset,
    processing_class=tokenizer,
    peft_config=peft_config,
)

try:
    train_result = trainer.train()
    metrics = train_result.metrics
    emit("EXPERIMENT_RESULT", metrics)
    emit("EXPERIMENT_STATUS", "COMPLETED")
    trainer.save_model()
    print(f"Training complete. Model saved to ./output")
except Exception as e:
    emit("EXPERIMENT_STATUS", f"CRASHED: {e}")
    raise
